name: Build a TiddlyWiki static site and deploy to GH Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-static-tw-publish:
    runs-on: ubuntu-latest

    env:
      SITE_URL: "https://inawa.youronly.one"
      SITE_NAME: "수랕 이나와 (Surat Inawa) | a Filipino adaption of Sejonggeul"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Build Static Pages
        run: |
          chmod +x $GITHUB_WORKSPACE/build.sh
          ./build.sh

      - name: Post-process tiddler pages
        run: node post-process.js

      - name: Add a nojekyll file
        run: touch $GITHUB_WORKSPACE/dist/.nojekyll

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
